version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: customer_product_db
      POSTGRES_USER: customer_product_db
      POSTGRES_PASSWORD: 123456@customer_product_db_yser
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: